#ifndef LOSEMYMIND_LANGUAGEFEATURES_H
#define LOSEMYMIND_LANGUAGEFEATURES_H

/// Macro for determining if GCC version is >= than X.Y
// #if defined(__GNUC__) && !CHECK_GCC_VERSION(4, 4)
// Do something
// #endif
#if defined(__GNUC__)
#define CHECK_GCC_VERSION(MAJOR, MINOR) \
        (__GNUC__ > MAJOR || (__GNUC__ == MAJOR && __GNUC_MINOR__ >= MINOR))
#else
#define CHECK_GCC_VERSION(MAJOR, MINOR) 0
#endif

/**
* These macros are for detect the compiler language (C/C++) standard.
*
* TARGET_LANGUAGE_FEATURES is set as follows:
*
* LANGUAGE_FEATURES_UNKNOWN	-> Unknown
* LANGUAGE_FEATURES_C1989	-> C89 - ANSI X3.159-1989
* LANGUAGE_FEATURES_C1990	-> C90 (same as C89) - ISO/IEC 9899:1990
* LANGUAGE_FEATURES_C1990_1	-> C95  (C90 + Normative Amendment 1) - ISO/IEC 9899/AMD1:1995
* LANGUAGE_FEATURES_C1994	-> C95  (C90 + Normative Amendment 1) - ISO/IEC 9899-1:1994
* LANGUAGE_FEATURES_C1995	-> C95  (C90 + Normative Amendment 1) - ISO/IEC 9899/AMD1:1995
* LANGUAGE_FEATURES_C1999	-> C99 - ISO/IEC 9899:1999
* LANGUAGE_FEATURES_C2011	-> C11 - ISO/IEC 9899:2011
* LANGUAGE_FEATURES_CPP1998	-> C++98 - ISO/IEC 14882:1998
* LANGUAGE_FEATURES_CPP2011	-> C++11 - ISO/IEC 14882:2011
* LANGUAGE_FEATURES_CPP2014	-> C++14 - ISO/IEC 14882:2014
* LANGUAGE_FEATURES_CPP2017	-> C++17 - ISO/IEC C++1z
*/

#define LANGUAGE_FEATURES_UNKNOWN	0
#define LANGUAGE_FEATURES_C1989		198990L
#define LANGUAGE_FEATURES_C1990		LANGUAGE_FEATURES_C1989
#define LANGUAGE_FEATURES_C1990_1	199409L
#define LANGUAGE_FEATURES_C1994		LANGUAGE_FEATURES_C1990_1
#define LANGUAGE_FEATURES_C1995		LANGUAGE_FEATURES_C1994
#define LANGUAGE_FEATURES_C1999		199901L
#define LANGUAGE_FEATURES_C2011		201112L
#define LANGUAGE_FEATURES_CPP1998	199711L
#define LANGUAGE_FEATURES_CPP2011	201103L
#define LANGUAGE_FEATURES_CPP2014	201402L
#define LANGUAGE_FEATURES_CPP2017	201403L

/**
* Detect the compiler language standard.
*/
#if defined(__cplusplus)
#	if (__cplusplus <= LANGUAGE_FEATURES_CPP1998)
#		define TARGET_LANGUAGE_FEATURES	LANGUAGE_FEATURES_CPP1998
#	elif (__cplusplus <= LANGUAGE_FEATURES_CPP2011)
#		define TARGET_LANGUAGE_FEATURES	LANGUAGE_FEATURES_CPP2011
#	elif (__cplusplus <= LANGUAGE_FEATURES_CPP2014)
#		define TARGET_LANGUAGE_FEATURES	LANGUAGE_FEATURES_CPP2014
#	elif (__cplusplus > LANGUAGE_FEATURES_CPP2014)
#		define TARGET_LANGUAGE_FEATURES	LANGUAGE_FEATURES_CPP2017
#	else
#		define TARGET_LANGUAGE_FEATURES	LANGUAGE_FEATURES_UNKNOWN
#   endif
#elif defined(__STDC_VERSION__)
#	if (__STDC_VERSION__ <= LANGUAGE_FEATURES_C1995)
#		define TARGET_LANGUAGE_FEATURES	LANGUAGE_FEATURES_C1995
#	elif (__STDC_VERSION__ <= LANGUAGE_FEATURES_C1999)
#		define TARGET_LANGUAGE_FEATURES	LANGUAGE_FEATURES_C1999
#	elif (__STDC_VERSION__ <= LANGUAGE_FEATURES_C2011)
#		define TARGET_LANGUAGE_FEATURES	LANGUAGE_FEATURES_C2011
#	else
#		define TARGET_LANGUAGE_FEATURES	LANGUAGE_FEATURES_UNKNOWN
#   endif
#elif defined(__STDC__)
#	if (__STDC__ <= LANGUAGE_FEATURES_C1990)
#		define TARGET_LANGUAGE_FEATURES	LANGUAGE_FEATURES_C1990
#	else
#		define TARGET_LANGUAGE_FEATURES	LANGUAGE_FEATURES_UNKNOWN
#   endif
#else
#		define TARGET_LANGUAGE_FEATURES	LANGUAGE_FEATURES_UNKNOWN
#endif


#ifdef _MSC_VER

#if _MSC_VER >= 1900
#	undef TARGET_LANGUAGE_FEATURES
#	define TARGET_LANGUAGE_FEATURES LANGUAGE_FEATURES_CPP2017
#elif _MSC_VER >= 1800
#	undef TARGET_LANGUAGE_FEATURES
#	define TARGET_LANGUAGE_FEATURES LANGUAGE_FEATURES_CPP2014
#elif _MSC_VER >= 1700
#	undef TARGET_LANGUAGE_FEATURES
#	define TARGET_LANGUAGE_FEATURES LANGUAGE_FEATURES_CPP2011
#elif _MSC_VER >= 1600
#	undef TARGET_LANGUAGE_FEATURES
#	define TARGET_LANGUAGE_FEATURES LANGUAGE_FEATURES_CPP1998
#endif
#endif

#if TARGET_LANGUAGE_FEATURES < LANGUAGE_FEATURES_CPP2011
#	define noexcept
#	define constexpr
#endif


#endif // LOSEMYMIND_LANGUAGEFEATURES_H
